/* eslint-disable react/prop-types */
/* It's kinda gay to remove this */

import Navbar from '@/app/Nav/Navbar';
//import Navbar from 'react-bootstrap/Navbar';
import React  from 'react';
export const metadata = {
        title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({ children }) {
   return (
      <html lang="en">
        <body>
            
            <Navbar/>
            {children}
            </body>
      </html>
    )
  }